image: golang:latest

variables:
  PROGRAM_ARGS: "2 600 200 200 3"

stages:
  - lint
  - test

format:
  stage: lint
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

.test:
  stage: test
  before_script:
    - mkdir -p bin
    - go build -o bin ./...

test-normal:
  extends: .test
  script:
    - ./bin/philo-go $PROGRAM_ARGS

test-error_arg:
  extends: .test
  script:
    - ./bin/philo-go
    - ./bin/philo-go 1
    - ./bin/philo-go -1
    - ./bin/philo-go 0 200 50 50 3
    - ./bin/philo-go asd 200 1 2 3
    - ./bin/philo-go 1 1 2 3 -1
    - ./bin/philo-go 1 1 2 3 0 2 1 2 3
  timeout: 5m
  allow_failure: true
  when: manual
